# ==============================================================================
# 核心基础配置 (Base Configuration)
# ==============================================================================
# 注意：多语言主题一般只需要在这里配置 theme, baseURL, languageCode
theme = "LoveIt"

# 必须使用全小写，否则可能导致 404 错误
baseURL = "https://damonfan3964.github.io/my-awesome-blog/"

# 设置网站默认语言为中文
defaultContentLanguage = "zh-cn"

# ==============================================================================
# 全局设置 (Global Settings)
# ==============================================================================

# 版权描述，仅仅用于 SEO
copyright = ""

# 是否使用 robots.txt
enableRobotsTXT = true

# 是否使用 git 信息 (建议保留，用于显示文章最后更新时间)
enableGitInfo = true

# 忽略一些构建错误
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# 分页配置
[pagination]
  pagerSize = 10

# Hugo 解析文档的配置
[markup]
  [markup.highlight]
    codeFences = true
    noClasses = true
  [markup.goldmark.renderer]
    # 允许在文档中直接使用 HTML 标签 (LoveIt 主题需要)
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# ==============================================================================
# LoveIt 主题全局参数 (Theme Global Parameters)
# ==============================================================================

[params]
  # 网站默认主题 ["auto", "light", "dark"]，推荐 auto 自动适应系统设置
  defaultTheme = "auto"
  
  # 网站描述, 用于 SEO
  description = "一位探索技术世界的新手的个人学习和分享记录。"
  
  # 作者配置
  [params.author]
    name = "Damon"
    email = "fy051213@gmail.com" 
    link = "https://github.com/DamonFAN3964"
    
  # 页面头部导航栏配置
  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      logo = ""
      name = "我的技术博客" # 导航栏显示的标题名称
      pre = "<i class='far fa-kiss-wink-heart fa-fw' aria-hidden='true'></i>"
      typeit = true # 启用打字机动画效果

  # 页面底部信息配置
  [params.footer]
    enable = true
    custom = 'Power by Hugo' # 自定义内容
    hugo = true
    copyright = true
    author = true
    since = 2025 # 你的博客创立年份
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # 主页信息设置
  [params.home]
    [params.home.profile]
      enable = true
      avatarURL = "/images/avatar.jpg" # 记得在 static/images/ 目录下放一张头像
      title = "Damon"
      subtitle = "永不停止学习的技术探索者" # 主页显示的副标题
      typeit = true
      social = true
      
  # 评论系统配置（默认启用 Valine，但需要配置 AppID/AppKey，否则无法使用）
  [params.page.comment]
    enable = true
    [params.page.comment.valine]
      enable = true
      # 请将 appId 和 appKey 替换为您在 LeanCloud 注册的真实信息
      appId = "QGzwQXOqs5JOhN4RGPOkR2mR-MdYXbMMI"
      appKey = "WBmoGyJtbqUswvfLh6L8iEBr"
      serverURLs = "https://valine.hugoloveit.com"


# ==============================================================================
# 多语言配置：只保留并完善 zh-cn (Chinese Simplified) 配置
# ==============================================================================
[languages]
  [languages.zh-cn]
    weight = 1
    languageCode = "zh-CN"
    languageName = "简体中文"
    hasCJKLanguage = true # 必须设为 true 以支持中文搜索和排版
    title = "我的个人技术博客"
    copyright = "本站内容遵循 CC BY-NC 4.0 许可协议."
    
    # 中文菜单配置
    [languages.zh-cn.menu]
      [[languages.zh-cn.menu.main]]
        weight = 1
        identifier = "posts"
        name = "所有文章"
        url = "/posts/"
      [[languages.zh-cn.menu.main]]
        weight = 2
        identifier = "tags"
        name = "标签"
        url = "/tags/"
      [[languages.zh-cn.menu.main]]
        weight = 3
        identifier = "categories"
        name = "分类"
        url = "/categories/"
      [[languages.zh-cn.menu.main]]
        weight = 4
        identifier = "about"
        name = "关于"
        url = "/about/"
      [[languages.zh-cn.menu.main]]
        weight = 5
        identifier = "github"
        pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
        name = "" # 留空只显示图标
        url = "https://github.com/DamonFAN3964" # 替换为你的 GitHub 主页
        title = "GitHub"

    # 中文参数 (覆盖全局配置)
    [languages.zh-cn.params]
      # 社交配置：请替换为您自己的账号 ID
      [languages.zh-cn.params.social]
        GitHub = "DamonFAN3964"
        Email = "fy051213@gmail.com"
        RSS = true
        # 如果您有其他账号，例如微博、知乎等，请取消注释并填写 ID
        # Weibo = "xxxx"
        # Zhihu = "xxxx"
        
      [languages.zh-cn.params.home]
        [languages.zh-cn.params.home.profile]
          subtitle = "一个简洁、优雅且高效的 Hugo 主题" # 保持 LoveIt 默认副标题，或替换为自己的座右铭
          
      # 搜索配置 (Algolia 默认配置，不需要更改，除非您自己注册了 Algolia 账号)
      [languages.zh-cn.params.search]
        enable = true
        type = "algolia"
        [languages.zh-cn.params.search.algolia]
          index = "index"
          appID = "GZT24PWKNT"
          searchKey = "634ab679e825b815de2663de38908f9d"


# ------------------------------------------------------------------------------
# 删除了示例配置中的 [languages.en] 区块，以确保只使用中文配置。
# ------------------------------------------------------------------------------